---
- name: Install Docker and Docker Compose on EC2 instances
  hosts: AWS_SERVER
  become: yes

  tasks:
    - block:
        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
            state: present

        - name: Install Docker
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present

        - name: Install Docker Compose
          get_url:
            url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 'u+x,g+x'
      when: ansible_os_family == "Debian"

    - block:
        - name: Install docker-ce (centos) via amazon-linux-extras packages
          shell: "amazon-linux-extras install docker -y"
        - name: Install dependencies
          yum:
            name:
             - docker
             - python3
             - python3-devel
             - libffi-devel
             - openssl-devel
            state: latest

        - name: Start Docker service
          service:
            name: docker
            state: restarted
            enabled: yes

        - name: Start Docker service
          service:
            name: docker
            state: started

        - name: Add user to Docker group
          user:
            name: ec2-user
            groups: docker
            append: yes

        - name: install Development Tools
          shell: yum groupinstall -y "Development Tools"

        - name: update python pip
          shell: python3 -m pip install -U pip

        - name: install docker-compose from pip
          shell: python3 -m pip install docker-compose
      when: ansible_os_family == "RedHat"